version: '3.3'
services:
  web:
    build: 
      context: ./apps/control-panel/frontend/
      dockerfile: web.dockerfile
    ports:
    - "5000:80"
#  database:
#    image: mongo
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: admin
#      MONGO_INITDB_DATABASE: db
#    volumes:
#    - waifudb:/data/db
#    - ./init-mongo.js:/docker-entrypoint-init.d
volumes:
  waifudb:
